"""add price_value and unit to news

Revision ID: 05d6a8f77faa
Revises: 4230e519dbdf
Create Date: 2026-01-16 10:37:02.329486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05d6a8f77faa'
down_revision: Union[str, Sequence[str], None] = '4230e519dbdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('price_value', sa.Float(), nullable=True))
    op.add_column('news', sa.Column('unit', sa.String(length=50), nullable=True))
    op.alter_column('news', 'urgency',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('news', 'risk_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'risk_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('news', 'urgency',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('news', 'unit')
    op.drop_column('news', 'price_value')
    # ### end Alembic commands ###
