"""add market_trends table

Revision ID: 4230e519dbdf
Revises: b19a20bae1b4
Create Date: 2026-01-16 09:22:23.149963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4230e519dbdf'
down_revision: Union[str, Sequence[str], None] = 'b19a20bae1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_unit', sa.String(length=50), nullable=True),
    sa.Column('industry_tag', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_trends_industry_tag'), 'market_trends', ['industry_tag'], unique=False)
    op.create_index(op.f('ix_market_trends_metric_name'), 'market_trends', ['metric_name'], unique=False)
    op.create_index(op.f('ix_market_trends_news_id'), 'market_trends', ['news_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_trends_news_id'), table_name='market_trends')
    op.drop_index(op.f('ix_market_trends_metric_name'), table_name='market_trends')
    op.drop_index(op.f('ix_market_trends_industry_tag'), table_name='market_trends')
    op.drop_table('market_trends')
    # ### end Alembic commands ###
