"""add published_at to market_trends

Revision ID: 5d1bd6be1472
Revises: ff570f34c6ac
Create Date: 2026-01-16 12:02:15.375580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d1bd6be1472'
down_revision: Union[str, Sequence[str], None] = 'ff570f34c6ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_trends', sa.Column('published_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.create_index(op.f('ix_market_trends_published_at'), 'market_trends', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_trends_published_at'), table_name='market_trends')
    op.drop_column('market_trends', 'published_at')
    # ### end Alembic commands ###
