"""add company_name to market_trends

Revision ID: 8f5a2436ed68
Revises: 5d1bd6be1472
Create Date: 2026-01-16 12:28:21.981951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f5a2436ed68'
down_revision: Union[str, Sequence[str], None] = '5d1bd6be1472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_trends', sa.Column('company_name', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_market_trends_company_name'), 'market_trends', ['company_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_trends_company_name'), table_name='market_trends')
    op.drop_column('market_trends', 'company_name')
    # ### end Alembic commands ###
