"""initial migration

Revision ID: b19a20bae1b4
Revises: 
Create Date: 2026-01-15 21:04:42.565056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b19a20bae1b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('impact_score', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('news', sa.Column('urgency', sa.String(length=50), nullable=True))
    op.add_column('news', sa.Column('risk_type', sa.String(length=100), nullable=True))
    op.add_column('news', sa.Column('action_recommendation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'action_recommendation')
    op.drop_column('news', 'risk_type')
    op.drop_column('news', 'urgency')
    op.drop_column('news', 'impact_score')
    # ### end Alembic commands ###
