"""add metric_type to market_trends

Revision ID: d0c44be0508f
Revises: 05d6a8f77faa
Create Date: 2026-01-16 11:22:43.207904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c44be0508f'
down_revision: Union[str, Sequence[str], None] = '05d6a8f77faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_trends', sa.Column('metric_type', sa.String(length=20), nullable=False, server_default='absolute'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_trends', 'metric_type')
    # ### end Alembic commands ###
