"""add published_at to news

Revision ID: ff570f34c6ac
Revises: d0c44be0508f
Create Date: 2026-01-16 12:00:36.792310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff570f34c6ac'
down_revision: Union[str, Sequence[str], None] = 'd0c44be0508f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('published_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.create_index(op.f('ix_news_published_at'), 'news', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_published_at'), table_name='news')
    op.drop_column('news', 'published_at')
    # ### end Alembic commands ###
